export default {
  computed: {
    appData () {
      return {
        title: 'ATS AGROCHEMICALS LTD',
        socialLinks: [
          { name: 'Facebook', icon: 'mdi-facebook', link: 'https://facebook.com', color: '#0F98F6' },
          { name: 'Instagram', icon: 'mdi-instagram', link: 'https://instagram.com', color: '#EF0075' },
          // { name: 'Twitter', icon: 'mdi-twitter', link: 'https://twitter.com', color: '#1A91DA' },
          { name: 'Youtube', icon: 'mdi-youtube', link: 'https://youtube.com', color: '#FE0200' },
          { name: 'LinkedIn', icon: 'mdi-linkedin', link: 'https://linkedin.com', color: '#0077B5' },
        ],
        contact: {
          phone: { value: '+260 9064 5707', icon: 'mdi-phone' },
          email: { value: 'info@atszambia.com', icon: 'mdi-email' },
        },
        recentNews: [
          'Lorem ipsum dolor sit amet, consectetur.',
          'Donec at nunc eget massa bibendum ultrices.',
          'Donec non sem fermentum, malesuada augue.',
          'Sed pharetra metus vitae diam blandit.',
          'Proin quis lacus lobortis, semper arcu.',
        ],
        blogPosts: [
          {
            title: 'Lorem ipsum dolor sit amet',
            text: 'Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima. Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima.',
            date: new Date().toLocaleDateString(),
            to: { name: 'Home' },
          },
          {
            title: 'Lorem ipsum dolor sit amet',
            text: 'Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima. Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima.',
            date: new Date(Date.now() - 1000 * 60 * 60 * 24).toLocaleDateString(),
            to: { name: 'Home' },
          },
          {
            title: 'Lorem ipsum dolor sit amet',
            text: 'Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima. Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima.',
            date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toLocaleDateString(),
            to: { name: 'Home' },
          },
        ],
        recentPosts: [
          {
            text: 'Lorem ipsum dolor sit amet, consectetur. Donec at nunc eget massa bibendum ultrices.',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric' }),
          },
          {
            text: 'Donec non sem fermentum, malesuada augue. Sed pharetra metus vitae diam blandit.',
            date: new Date(Date.now() - 1000 * 60 * 60 * 24).toLocaleDateString('en-US', { month: 'long', day: 'numeric' }),
          },
        ],
        crops: [
          {
            id: 1,
            src: require('@/assets/team/cabbage.jpg'),
            title: 'Cabbage',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'mountain',
          },
          {
            id: 2,
            src: require('@/assets/team/tomatoes.jpg'),
            title: 'Tomatoes',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'fire',
          },
          {
            id: 3,
            src: require('@/assets/team/sugarcane.jpg'),
            title: 'Sugar Cane',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'mountain',
          },
          {
            id: 4,
            src: require('@/assets/team/maize.jpg'),
            title: 'Corn',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
        ],
        projects: [
          {
            id: 1,
            src: require('@/assets/products/efekto/ants.png'),
            title: 'No Insects Indoors - Ants',
            subtitle: 'Public Health',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Control of household insects such as Ants, Cockroaches, Bedbugs, Fish moths in homes & industries',
            tags: ['tag', 'tag', 'tag'],
            category: 'efekto',
          },
          {
            id: 2,
            src: require('@/assets/products/efekto/cockroaches.png'),
            title: 'No Insects Indoors - Cockroaches',
            subtitle: 'Public Health',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Control of household insects such as Ants, Cockroaches, Bedbugs, Fish moths in homes & industries',
            tags: ['tag', 'tag', 'tag'],
            category: 'efekto',
          },
          {
            id: 3,
            src: require('@/assets/products/efekto/contact-stomach-insecticide.png'),
            title: 'No Insects Indoors - Contact-stomach',
            subtitle: 'Public Health',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Control of household insects such as Ants, Cockroaches, Bedbugs, Fish moths in homes & industries',
            tags: ['tag', 'tag', 'tag'],
            category: 'efekto',
          },
          {
            id: 4,
            src: require('@/assets/products/efekto/flying-insects.png'),
            title: 'No Insects Indoors - Flying insects',
            subtitle: 'Public Health',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Control of household insects such as Ants, Cockroaches, Bedbugs, Fish moths in homes & industries',
            tags: ['tag', 'tag', 'tag'],
            category: 'efekto',
          },
          {
            id: 5,
            src: require('@/assets/products/insectides/bazuka.png'),
            title: 'BAZUKA 500 EC',
            subtitle: 'Chloropyrifos 450g/l + Cypermethrin 50g/l',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Controls Aphids, Redscale, american bollworm, Thrips in Citrus, Cereals & Vegetables.',
            tags: ['tag', 'tag', 'tag'],
            category: 'insectides',
          },
          {
            id: 6,
            src: require('@/assets/products/insectides/drone.png'),
            title: 'Drone 200 SL',
            subtitle: 'Acetamiprid 222g/l',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Insectidcide for the control of Aphids, Jassids, Melly Bugs & Scales in Cotton, Maize, Tobacco and Veggies.',
            tags: ['insectides', 'products'],
            category: 'insectides',
          },
          {
            id: 7,
            src: require('@/assets/products/insectides/fapronil.png'),
            title: 'FAPRONIL 200 EC',
            subtitle: 'Fipronil 200g/l',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Controls Termites, White Ants , White Grub in All crops and Building foundation',
            tags: ['insectides', 'products'],
            category: 'insectides',
          },
          {
            id: 8,
            src: require('@/assets/products/insectides/majestic.png'),
            title: 'MAJESTIC EC',
            subtitle: 'Emamectin Benzoate 12g/kg + Imidacloprid 50g/l',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Controls Fall army worm, Tuta, Bollworms, Aphids & others in Fruits, Vegetables, Maize & Soybean',
            tags: ['insectides', 'products'],
            category: 'insectides',
          },
          {
            id: 9,
            src: require('@/assets/projects/kseniya-petukhova-_wj5Jd-AaK4-unsplash.jpg'),
            title: 'Kseniya Petukhova',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'mountain',
          },
          {
            id: 10,
            src: require('@/assets/projects/mike-erskine-S_VbdMTsdiA-unsplash.jpg'),
            title: 'Mike Erskine',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'fire',
          },
          {
            id: 11,
            src: require('@/assets/projects/patrick-boucher-0ccc00jMW1U-unsplash.jpg'),
            title: 'Patrick Boucher',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'day',
          },
          {
            id: 12,
            src: require('@/assets/projects/robson-hatsukami-morgan-RTKaEcGKarQ-unsplash.jpg'),
            title: 'Robson Hatsukami Morgan',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'fire',
          },
          {
            id: 13,
            src: require('@/assets/projects/sahin-yesilyaprak-V7uP-XzqX18-unsplash.jpg'),
            title: 'Sahin Yesilyaprak',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'fire',
          },
          {
            id: 14,
            src: require('@/assets/projects/sayan-nath-MCfy9IZivT0-unsplash.jpg'),
            title: 'Sayan Nath',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'mountain',
          },
          {
            id: 15,
            src: require('@/assets/projects/thomas-aeschleman-BG8te7fVCqU-unsplash.jpg'),
            title: 'Thomas Aeschleman',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 16,
            src: require('@/assets/projects/twitter-praizist-PDNc3fFFrYk-unsplash.jpg'),
            title: '@praizist Twitter',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'day',
          },
        ],

        instagramPosts: [
          {
            id: 1,
            src: require('@/assets/instagram/ahmad-kadhim-GeHVEDrqMB8-unsplash.jpg'),
          },
          {
            id: 2,
            src: require('@/assets/instagram/ciocan-ciprian-XGny9I-k9RM-unsplash.jpg'),
          },
          {
            id: 3,
            src: require('@/assets/instagram/lukasz-szmigiel-dAgtO5H8cXg-unsplash.jpg'),
          },
          {
            id: 4,
            src: require('@/assets/instagram/malka-l0m2p_k5VJ8-unsplash.jpg'),
          },
          {
            id: 5,
            src: require('@/assets/instagram/max-delsid-8-Aght_oHog-unsplash.jpg'),
          },
          {
            id: 6,
            src: require('@/assets/instagram/ricardo-gomez-angel-SAJD-Q4FntE-unsplash.jpg'),
          },
        ],
        tweets: [
          {
            id: 1,
            author: '@vuetifyjs',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam rhoncus sit amet nisl sollicitudin auctor. Nam dapibus odio neque, sed proin.',
          },
          {
            id: 2,
            author: '@vuetifyjs',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam rhoncus sit amet nisl sollicitudin auctor. Nam dapibus odio neque, sed proin.',
          },
        ],
        tags: [
          'Portfolio',
          'Theme',
          'Camping',
          'Forest',
          'Hiking',
        ],
        relatedPosts: [
          {
            id: 1,
            title: 'Title',
            author: 'John Smith',
            src: require('@/assets/projects/everett-mcintire-BPCsppbNRMI-unsplash.jpg'),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst.',
            date: new Date().toLocaleDateString(),
            commentCount: 10,
          },
          {
            id: 2,
            title: 'Title',
            author: 'John Smith',
            src: require('@/assets/projects/adrian-TvN54bnuQg8-unsplash.jpg'),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst.',
            date: new Date().toLocaleDateString(),
            commentCount: 10,
          },
          {
            id: 3,
            title: 'Title',
            author: 'John Smith',
            src: require('@/assets/projects/robson-hatsukami-morgan-RTKaEcGKarQ-unsplash.jpg'),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst.',
            date: new Date().toLocaleDateString(),
            commentCount: 10,
          },
        ],
      }
    },
  },
}
